# Generated by Django 3.1.2 on 2020-10-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.bug'),
        ),
    ]
