# Generated by Django 3.1.2 on 2020-10-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(choices=[('REPORTER', 'Reporter'), ('DEVELOPER', 'Developer'), ('REVIEWER', 'Reviewer'), ('TRIAGER', 'Triager')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
                ('developer_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user')),
            ],
            options={
                'db_table': 'bugs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.role'),
        ),
    ]
