# Generated by Django 3.1.2 on 2020-10-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201007_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000, null=True)),
                ('bug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bug')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
