# Generated by Django 3.1.2 on 2020-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201027_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bug',
        ),
        migrations.AddField(
            model_name='comment',
            name='bug_id',
            field=models.IntegerField(null=True),
        ),
    ]
